apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-latest-ref
  labels:
    app: spring-latest-ref
spec:
  ingressClassName: nginx
  rules:
    #  - host: spring-latest-ref.local
    - http:
        paths:
          - path: /auta
            pathType: Prefix
            backend:
              service:
                name: spring-latest-ref
                port:
                  number: 8080
          - path: /actuator
            pathType: Prefix
            backend:
              service:
                name: spring-latest-ref
                port:
                  number: 8080
